name: build-and-push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry.zachklingbeil.com
        uses: docker/login-action@v3
        with:
          registry: registry.zachklingbeil.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          pull: true
          tags: |
            registry.zachklingbeil.com/pathless:latest
            registry.zachklingbeil.com/pathless:${{ github.sha }}
          cache-from: type=gha
          # cache-to: type=gha,mode=max

      - name: Log out from registry
        run: docker logout registry.zachklingbeil.com
