name: tag and release

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: self-hosted
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4

            - name: Get latest tag and bump version
              id: bump_version
              run: |
                  latest_tag=$(git describe --tags --abbrev=0 --match '1.[0-9]*' 2>/dev/null || echo "")

                  if [ -z "$latest_tag" ]; then
                      new_version="1.01"
                  else
                      minor=$(echo "$latest_tag" | cut -d. -f2)
                      new_version="1.$((minor + 1))"
                  fi

                  echo "Previous: ${latest_tag:-none} → New: $new_version"
                  echo "new_tag=$new_version" >> $GITHUB_OUTPUT

            - name: Create and push tag
              run: |
                  git tag ${{ steps.bump_version.outputs.new_tag }}
                  git push origin ${{ steps.bump_version.outputs.new_tag }}

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ steps.bump_version.outputs.new_tag }}
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
